language: node_js
node_js:
- 0.8
notifications:
  emai: false
  slack:
    secure: NvI7ciAdnH5P3zi5PVRaOPMoWooEuN65NXIjqpgr+khjIokj2u5d17eScV/Xom1yJXhfayzRSXVu3/mO092MjNMH6p6dBbzixulQOcURjGxiVRB/PKoIKveUqtkc0T0FuM3AhGeOHR4XwOu0EoH69qvAuaZ7G7sJYN03ZXQ2ADkD2MX2g+w4b9bCyoSKrRJ8jbpAu1OEfBaiHp4rbmedDd9UKIaiHqE2ugxWATbx5rhju/TsNAkQ2oyEldz/jRQHALqc2BO4L9c3XWIRep+K26E9xHDr4HCmjkDFEutPkGJ6b9vnKA8Zy2KLMsAVJMrltw7WyIgQDLdYbmAypdHbiC4JgGAhnQ9kRjunXhQXMWEd/w8E2u9HbLWfibLufuPe7Jl8JmK1z4HC2ltYOCN7rZojVspT+4/VYC+S7lQCZ8h0LEPE/OxbQcOr0i8QK0FPDpzlxM9kqMV529Or78tiyONkHMzsuHdcExndbPCn0qlUavtusLRP40YRD2d8lQP2oozy5P0df8lQLSyZdQllDvRmheF+jD9YL0HvrcBJVeyP5iBXT8t70EPXwccl5l4G1uPd7eUzgpajLP9kLeAix0rqcnJKAyCrWvX2S1NKE8dLNPgCS7ztUjiDsPHgQT+NI3jMrrFbwdBTeI8MlnVshCPwdrHOTbudAEHs0FU+3jw=
